version: "3"

services:
  loggy:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 6

  not_loggy:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 6
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  nginx:
    image: nginx:latest